# Generated by Django 5.2.17 on 2026-08-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_studentprofile_bio_studentprofile_class_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/logos/'),
        ),
    ]
