# Generated by Django 5.2.17 on 2026-08-31 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_clubprofile_bio_clubprofile_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
