# Generated by Django 5.2.17 on 2026-09-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_clubprofile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
